<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">

<head>

<meta charset="utf-8" />
<meta name="generator" content="quarto-1.3.433" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />


<title>Answers Aggregated Session - Day2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<!-- htmldependencies:E3FAD763 -->


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Answers Aggregated Session - Day2</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="practical-exercise-aggregated-data---answers-day-2" class="level1">
<h1>Practical Exercise Aggregated data - Answers Day 2</h1>
<p>Here are the answers to the 19 questions of the Practical Exercise of the Aggregated data session (Day 2). If you have any questions, feel free to email me at blanca.paniello@isglobal.org</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># YOU CAN SKIP THIS IF YOU HAVE ALREADY RUN THE DATA </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)       </span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: &#39;dplyr&#39;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from &#39;package:stats&#39;:

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from &#39;package:base&#39;:

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode" id="cb5"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate) </span></code></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: &#39;lubridate&#39;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from &#39;package:base&#39;:

    date, intersect, setdiff, union</code></pre>
</div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ISOweek) </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Change to your folder</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/bpaniello/Documents/KI_Oct2025&quot;</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;datatable_temp_es_se_fr.RData&quot;</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure columns are numeric</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>datatable_temp<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(datatable_temp<span class="sc">$</span>year)  <span class="co"># Year of observation</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>datatable_temp<span class="sc">$</span>woy  <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(datatable_temp<span class="sc">$</span>woy)   <span class="co"># Week of year</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>datatable_temp<span class="sc">$</span>temp <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(datatable_temp<span class="sc">$</span>temp)  <span class="co"># Temperature (Kelvin)</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert temperature from Kelvin to Celsius</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>datatable_temp<span class="sc">$</span>temp <span class="ot">&lt;-</span> datatable_temp<span class="sc">$</span>temp <span class="sc">-</span> <span class="fl">273.15</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Load weekly mortality data</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;datatable_mort_es_se_fr.RData&quot;</span>)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure numeric format</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>datatable_mort<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(datatable_mort<span class="sc">$</span>year)</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>datatable_mort<span class="sc">$</span>woy  <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(datatable_mort<span class="sc">$</span>woy)   <span class="co"># Week of year</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>datatable_mort<span class="sc">$</span>mort <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(datatable_mort<span class="sc">$</span>mort)  <span class="co"># Mortality count</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge mortality with combined temperature table</span></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>datatable_data <span class="ot">&lt;-</span> <span class="fu">left_join</span>(datatable_mort, datatable_temp,</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>                            <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;location&quot;</span>, <span class="st">&quot;year&quot;</span>, <span class="st">&quot;woy&quot;</span>))</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean up memory by removing temporary datasets</span></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(datatable_mort, datatable_temp)</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Add actual calendar date (Thursday of each ISO week) </span></span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a><span class="co"># ISOweek format: YYYY-Www-d (d = weekday, 4 = Thursday)</span></span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>datatable_data<span class="sc">$</span>date <span class="ot">&lt;-</span> <span class="fu">ISOweek2date</span>(</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">paste0</span>(datatable_data<span class="sc">$</span>year, <span class="st">&quot;-W&quot;</span>, </span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>         <span class="fu">sprintf</span>(<span class="st">&quot;%02d&quot;</span>, datatable_data<span class="sc">$</span>woy), <span class="st">&quot;-&quot;</span>, <span class="dv">4</span>)</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;METATABLE_es_se_fr.RData&quot;</span>)</span></code></pre></div>
</div>
<section id="question-1-how-many-rows-and-columns-are-in-the-dataset" class="level3">
<h3>Question 1: How many rows and columns are in the dataset?</h3>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Number of rows =&quot;</span>, <span class="fu">nrow</span>(datatable_data), <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of rows = 146112 </code></pre>
</div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Number of columns =&quot;</span>, <span class="fu">ncol</span>(datatable_data), <span class="st">&quot;</span><span class="sc">\n\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of columns = 6 </code></pre>
</div>
</div>
<p>We have 146112 rows (observations) and 6 columns including location, year, week of the year (woy), mortality, temperature and date.</p>
</section>
<section id="question-2-how-many-regions-are-included-in-total-and-per-country" class="level3">
<h3>Question 2: How many regions are included? (in total and per country?)</h3>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>regions_total <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(datatable_data<span class="sc">$</span>location)) </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Total number of regions:&quot;</span>, regions_total, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Total number of regions: 176 </code></pre>
</div>
<div class="sourceCode" id="cb15"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>regions_by_country <span class="ot">&lt;-</span> METATABLE <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(nuts0) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n_regions =</span> <span class="fu">n_distinct</span>(location)) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(n_regions))</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(regions_by_country)</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  nuts0 n_regions
  &lt;chr&gt;     &lt;int&gt;
1 FR           96
2 ES           59
3 SE           21</code></pre>
</div>
</div>
<p>In total, we have 176 regions among three countries. For France, we have data for 96 regions. For Spain, we have data for 59 regions. For Sweden, we have data for 21 regions.</p>
</section>
<section id="question-3-what-is-the-total-mortality-across-all-regions-and-per-country" class="level3">
<h3>Question 3: What is the total mortality across all regions? And per country?</h3>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Overall</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">&quot;Total Mortality: &quot;</span>, <span class="fu">sum</span>(datatable_data<span class="sc">$</span>mort, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] &quot;Total Mortality: 17281315&quot;</code></pre>
</div>
<div class="sourceCode" id="cb19"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spain</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>metadata_es <span class="ot">&lt;-</span> METATABLE <span class="sc">%&gt;%</span> </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(METATABLE<span class="sc">$</span>nuts0 <span class="sc">==</span> <span class="st">&quot;ES&quot;</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>datetable_es <span class="ot">&lt;-</span> datatable_data <span class="sc">%&gt;%</span> </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(location <span class="sc">%in%</span> metadata_es<span class="sc">$</span>location)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">&quot;Total Mortality Spain: &quot;</span>, <span class="fu">sum</span>(datetable_es<span class="sc">$</span>mort, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] &quot;Total Mortality Spain: 9182220&quot;</code></pre>
</div>
<div class="sourceCode" id="cb21"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sweden</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>metadata_se <span class="ot">&lt;-</span> METATABLE <span class="sc">%&gt;%</span> </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(METATABLE<span class="sc">$</span>nuts0 <span class="sc">==</span> <span class="st">&quot;SE&quot;</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>datetable_se <span class="ot">&lt;-</span> datatable_data <span class="sc">%&gt;%</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(location <span class="sc">%in%</span> metadata_se<span class="sc">$</span>location)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">&quot;Total Mortality Sweden: &quot;</span>, <span class="fu">sum</span>(datetable_se<span class="sc">$</span>mort, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] &quot;Total Mortality Sweden: 2080796&quot;</code></pre>
</div>
<div class="sourceCode" id="cb23"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># France</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>metadata_fr <span class="ot">&lt;-</span> METATABLE <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(METATABLE<span class="sc">$</span>nuts0 <span class="sc">==</span> <span class="st">&quot;FR&quot;</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>datetable_fr <span class="ot">&lt;-</span> datatable_data <span class="sc">%&gt;%</span> </span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(location <span class="sc">%in%</span> metadata_fr<span class="sc">$</span>location)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste0</span>(<span class="st">&quot;Total Mortality France: &quot;</span>, <span class="fu">sum</span>(datetable_fr<span class="sc">$</span>mort, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] &quot;Total Mortality France: 6018299&quot;</code></pre>
</div>
</div>
<p>Overall, we have a total of 17,281,315 deaths among the three countries. Spain has 9,182,220 deaths in total, Sweden has 2,080,796 deaths and France 6,018,299 deaths, thus being Spain the country with more all-cause total mortality.</p>
</section>
<section id="question-4-what-is-the-time-range-earliest-and-latest-dates-covered-by-the-data-total-and-per-country" class="level3">
<h3>Question 4: What is the time range (earliest and latest dates) covered by the data (total and per country)?</h3>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(datatable_data<span class="sc">$</span>date))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
&quot;2000-01-06&quot; &quot;2008-10-02&quot; &quot;2015-01-15&quot; &quot;2013-09-24&quot; &quot;2019-01-10&quot; &quot;2022-12-29&quot; </code></pre>
</div>
<div class="sourceCode" id="cb27"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spain</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(datetable_es<span class="sc">$</span>date))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
&quot;2000-01-06&quot; &quot;2005-10-04&quot; &quot;2011-07-03&quot; &quot;2011-07-03&quot; &quot;2017-03-31&quot; &quot;2022-12-29&quot; </code></pre>
</div>
<div class="sourceCode" id="cb29"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sweden</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(datetable_se<span class="sc">$</span>date))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
&quot;2000-01-06&quot; &quot;2005-10-04&quot; &quot;2011-07-03&quot; &quot;2011-07-03&quot; &quot;2017-03-31&quot; &quot;2022-12-29&quot; </code></pre>
</div>
<div class="sourceCode" id="cb31"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># France</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(datetable_fr<span class="sc">$</span>date))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
&quot;2013-01-03&quot; &quot;2015-07-02&quot; &quot;2017-12-31&quot; &quot;2017-12-31&quot; &quot;2020-07-02&quot; &quot;2022-12-29&quot; </code></pre>
</div>
</div>
<p>Overall, the earliest date is 6th of January of 2000 and the latest date is 29th of December of 2022. Moreover, we see that, although Spain and Sweden have the same data length, France has data from the 3rd of January of 2013. Although this is not ideal, this is quite common in aggregated data studies since different locations and countries have registries starting at different data points.</p>
<p>Finally, we will restrict our data to end of 2019 for simplicity reasons since we might find some abnormal fluctuations due to the COVID-19 pandemic.</p>
</section>
<section id="question-5-what-does-the-distribution-of-temperature-temp-look-like-overall-and-by-country" class="level3">
<h3>Question 5: What does the distribution of temperature (temp) look like overall and by country?</h3>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Overall </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(datatable_data<span class="sc">$</span>temp))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-22.988   7.411  12.937  12.710  18.287  33.974 </code></pre>
</div>
<div class="sourceCode" id="cb35"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>datatable_with_meta <span class="ot">&lt;-</span> datatable_data <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(dplyr<span class="sc">::</span><span class="fu">select</span>(METATABLE, location, nuts0), <span class="at">by =</span> <span class="st">&quot;location&quot;</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Spain</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(datetable_es<span class="sc">$</span>temp))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -4.445   9.975  15.392  15.170  20.310  33.974 </code></pre>
</div>
<div class="sourceCode" id="cb37"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sweden</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(datetable_se<span class="sc">$</span>temp))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-22.9878   0.8619   6.4840   6.7513  13.6254  24.1023 </code></pre>
</div>
<div class="sourceCode" id="cb39"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># France</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(datetable_fr<span class="sc">$</span>temp))</span></code></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -8.649   7.239  11.872  12.230  17.438  29.906 </code></pre>
</div>
<div class="sourceCode" id="cb41"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional graph</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datatable_with_meta, <span class="fu">aes</span>(<span class="at">x =</span> nuts0, <span class="at">y =</span> temp)) <span class="sc">+</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">xlab</span>(<span class="st">&quot;Country (nuts0)&quot;</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">&quot;Weekly mean temp&quot;</span>) <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="st">&quot;Temp distribution by country&quot;</span>)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="Answers_AggregatedSession_Day2_BPC_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672" /></p>
</div>
</div>
<p>Overall, the minimum temperature is -22.98ºC and the maximum is 33.97ºC.</p>
<p>For Spain, the minimum temperature is -4.44ºC and the maximum is 33.97ºC. For Sweden, the minimum temperature is -22.98ºC and the maximum is 24.10ºC. For France, the minimum temperature is -8.64ºC and the maximum is 29.90ºC.</p>
<p>Therefore, the overall minimum temperature comes from Sweden and the maximum from Spain.</p>
</section>
<section id="question-6-plot-the-time-series-of-weekly-mortality-and-of-weekly-mean-temperature-for-an-average-year.-do-you-notice-any-seasonal-patterns-in-either-series" class="level3">
<h3>Question 6: Plot the time series of weekly mortality and of weekly mean temperature for an average year. Do you notice any seasonal patterns in either series?</h3>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="sourceCode r cell-code"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Average across years by week-of-year</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>avg_by_woy <span class="ot">&lt;-</span> datatable_data <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(woy) <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_mort =</span> <span class="fu">mean</span>(mort, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">mean_temp =</span> <span class="fu">mean</span>(temp, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(woy)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>mort <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(avg_by_woy, <span class="fu">aes</span>(<span class="at">x=</span>woy)) <span class="sc">+</span></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> mean_mort)) <span class="sc">+</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Average-year weekly mortality (by week-of-year)&quot;</span>)</span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-13"><a href="#cb42-13" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(avg_by_woy, <span class="fu">aes</span>(<span class="at">x=</span>woy)) <span class="sc">+</span></span>
<span id="cb42-14"><a href="#cb42-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> mean_temp), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb42-15"><a href="#cb42-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Average-year weekly mean temperature (by week-of-year)&quot;</span>)</span>
<span id="cb42-16"><a href="#cb42-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-17"><a href="#cb42-17" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mort); <span class="fu">print</span>(temp)</span></code></pre></div>
<div class="cell-output-display">
<p><img src="Answers_AggregatedSession_Day2_BPC_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672" /></p>
</div>
<div class="cell-output-display">
<p><img src="Answers_AggregatedSession_Day2_BPC_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672" /></p>
</div>
</div>
<p>For the average-year weekly mortality, we observe the mortality is higher in winter (first and last weeks of the year), while the mortality is lower during the summer. Nonetheless, we observe that during the central months of summer (July to August) we can see slight peaks of mortality, likely related to heat (and heatwaves).For mortality, there’s a clear trend with higher temperatures during the summer and lower temperatures during the winter, as expected.</p>
</section>
<section id="question-7-what-type-of-regression-model-is-used-in-this-stage-and-why-is-it-suitable-for-mortality-counts" class="level3">
<h3>Question 7: What type of regression model is used in this stage, and why is it suitable for mortality counts?</h3>
<p>We use a quasi-Poisson regression within a generalized linear model (GLM). This is suitable because mortality is count data, which follows a Poisson distribution, but in practice mortality counts are often over dispersed (variance larger than the mean). The quasi-Poisson accounts for this extra variability while retaining interpretability.</p>
</section>
<section id="question-8-why-do-we-include-a-seasonality-term-nswop-df-in-the-model" class="level3">
<h3>Question 8: Why do we include a seasonality term (ns(wop, df = …)) in the model?</h3>
<p>The natural spline for week-of-year (or similar seasonal variable) controls for long-term seasonal patterns such as influenza peaks or winter mortality. Without this adjustment, the estimated temperature–mortality association could be confounded by underlying seasonal cycles.</p>
</section>
<section id="question-9-what-are-the-two-dimensions-that-are-combined-in-a-cross-basis-function" class="level3">
<h3>Question 9: What are the two dimensions that are combined in a cross-basis function?</h3>
<p>In the cross-basis function we combine two dimensions, the exposure-response association (temperature and mortality) and the lag-response association (delayed effects of temperature on mortality). This two-dimensional function allows us to capture both the shape of the risk curve and how long the effect persists.</p>
</section>
<section id="question-10-why-is-it-important-to-include-lagged-effects-when-modelling-temperature-and-mortality" class="level3">
<h3>Question 10: Why is it important to include lagged effects when modelling temperature and mortality?</h3>
<p>Temperature does not only affect mortality on the same day. Cold-related mortality often occurs with a delay (e.g. several days or weeks later due to infections or cardiovascular stress), while heat-related mortality tends to be more immediate. Ignoring lags would underestimate or miss-attribute the true effect of temperature on mortality.</p>
</section>
<section id="question-11-how-are-the-location-of-knots-for-temperature-defined-in-the-script" class="level3">
<h3>Question 11: How are the location of knots for temperature defined in the script?</h3>
<p>Knots are placed at the 10th, 50th, and 90th percentiles of each location’s temperature distribution. This ensures flexibility in the spline while adapting to the local climate range.</p>
</section>
<section id="question-12-what-do-the-cen-and-at-arguments-control" class="level3">
<h3>Question 12: What do the cen and at arguments control?</h3>
<p>‘at’ specifies the temperatures where predictions (e.g., relative risks) are calculated. ‘cen’ sets the centering temperature — the reference point for relative risks (usually the Minimum Mortality Temperature, MMT).</p>
</section>
<section id="question-13-whats-the-purpose-of-centering-at-the-minimum-mortality-temperature-mmt" class="level3">
<h3>Question 13: What’s the purpose of centering at the Minimum Mortality Temperature (MMT)?</h3>
<p>By centering at the MMT, the model compares risks at other temperatures relative to the point of lowest mortality risk. This provides a meaningful reference, avoiding arbitrary choices like the mean or median temperature.</p>
</section>
<section id="question-14-how-does-the-model-determine-the-minimum-mortality-temperature-mmt" class="level3">
<h3>Question 14: How does the model determine the Minimum Mortality Temperature (MMT)?</h3>
<p>The MMT is identified empirically from the exposure–response curve: it is the temperature at which the predicted relative risk of mortality is lowest. The model searches across the fitted curve and selects this minimum.</p>
</section>
<section id="question-15-why-do-we-need-to-save-both-the-coefficients-and-covariance-matrices-for-the-second-stage-meta-analysis" class="level3">
<h3>Question 15: Why do we need to save both the coefficients and covariance matrices for the second-stage meta-analysis?</h3>
<p>The coefficients represent the estimated associations for each location. The covariance matrices capture the uncertainty and correlation between coefficients within each location. Both are necessary so the second-stage meta-analysis (e.g. mixmeta) can properly weight each region by its precision and account for uncertainty.</p>
</section>
<section id="question-16-based-on-the-wald-test-results-do-all-meta-predictors-explain-part-of-the-association-assess-their-significance." class="level3">
<h3>Question 16: Based on the Wald-test results, do all meta predictors explain part of the association? Assess their significance.</h3>
<p>If the Wald test shows that the p-values for meta-predictors are below 0.05, then they significantly explain part of the heterogeneity in temperature–mortality associations. This means the variation across regions is partly attributable to these predictors. In our case, both TEMP_AVG and TEMP_IQR are significant.</p>
</section>
<section id="question-17-what-differences-do-you-observe-between-the-regional-non-meta-and-meta-analysis-plots" class="level3">
<h3>Question 17: What differences do you observe between the regional (non-meta) and meta-analysis plots?</h3>
<p>Regional estimates alone tend to have wider, more unstable confidence intervals. After pooling with meta-analysis, the estimates are shrunk toward the overall mean, resulting in narrower confidence intervals and smoother curves. This reflects borrowing strength across locations by applying the mixmeta and blups functions.</p>
</section>
<section id="question-18-compare-regions-of-sweden-france-and-spain.-what-differences-appear-in-the-exposure-response-curves-how-does-the-regional-cumulative-curve-differ" class="level3">
<h3>Question 18: Compare regions of Sweden, France, and Spain. What differences appear in the exposure-response curves? How does the regional cumulative curve differ?</h3>
<p>Generally we can observe that the confidence intervals are bigger in extreme temperatures. This is because there’s less days in the year getting to such degrees, thus having a lower sample.</p>
<p>For Spain, we can observe that most regions have an MMT between 15 and 25 degrees with a sharp increase for warm temperatures and a slight progressive increase in moderate cold temperatures and a steeper increase in extreme temperatures. This same trend can be observed for regions in France. Nonetheless, in most of the Swedish regions we observe that the MMT is around 20ºC and then an increase in colder temperatures and no heat-related mortality. This is because most of the regions of Sweden do not get to such higher temperatures, thus only showing cold-related mortality.</p>
</section>
<section id="question-19-interpret-the-final-cumulative-curve-for-the-three-countries." class="level3">
<h3>Question 19: Interpret the final cumulative curve for the three countries.</h3>
<p>In the overall cumulative curve we observe that the MMT is in 18.36ºC with heat-related mortality getting to a RR of 1.15 and a cold-related mortality of nearly 1.35. On one hand, for heat-related mortality (temperatures above the MMT) we see big confidence intervals. This is due to the fact that most regions in Sweden do not have heat-related mortality, which means that the number of contributing regions is lower and there’s higher variability regarding the risk in those temperatures among all the regions.</p>
<p>When assessing cold-related mortality, we observe a progressive increase in moderate cold temperatures and slight steeper increase in more extreme temperatures. For moderate cold temperatures we can see that the confidence interval is bigger than the extreme cold temperatures. This is because the variability in the risk in extreme temperatures is lower and more consistent across regions, thus having smaller CIs than in the moderate temperatures, where there’s bigger variability among regions.</p>
<p>Overall, as we can see in the differences between regions and countries, we need to interpret these overall curves in a conservative way as they are the “average” representation of all our units but do not necessarily represent the risk in each region. That’s why the overall evaluation needs to be done with the regional curves too to have a better insight of the temperature-related risks. Regional curves remain essential to capture local vulnerabilities and climate realities.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id = "quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->

</body>

</html>